research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information on how the topic
    is relevant to the Atoma Network, and if it can be either used to improve the
    technology around the Atoma Network, or if it is some technology that can be built
    on top of the Atoma Network decentralized AI compute layer.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'

atoma_community_tweet_task:
  description: >
    Create a tweet that is tailored to the Atoma community, about {topic}. It should be engaging,
    concise and professional. The goal is to promote Atoma's technology, vision,
    and future growth. Albeit being professional, you can also be funny and creative,
    always promoting Atoma's interests in the best way possible.
  expected_output: >
    A tweet that is engaging for the Atoma community.
